const tailorsData = [
  {
    id: "TL001",
    name: "Ali Raza",
    phone: "0301-1234567",
    city: "Lahore",
    experience: "8 Years",
    specialization: "Bridal Wear",
    currentOrders: 175,

    completedOrders: 245,
    activeOrders: 6,
    rating: 4.9,
    status: "Busy",
  },
  {
    id: "TL002",
    name: "Ahmed Khan",
    phone: "0321-4567890",
    city: "Karachi",
    experience: "5 Years",
    specialization: "Men's Suits",
    completedOrders: 180,
    currentOrders: 175,

    activeOrders: 0,
    rating: 4.7,
    status: "Available",
  },
  {
    id: "TL003",
    name: "Usman Tariq",
    phone: "0333-9876543",
    city: "Islamabad",
    experience: "6 Years",
    specialization: "Casual Wear",
    currentOrders: 175,

    completedOrders: 160,
    activeOrders: 4,
    rating: 4.8,
    status: "Busy",
  },
  {
    id: "TL004",
    name: "Bilal Ahmed",
    phone: "0345-6789123",
    city: "Faisalabad",
    experience: "10 Years",
    currentOrders: 175,

    specialization: "Luxury Dresses",
    completedOrders: 320,
    activeOrders: 0,
    rating: 5.0,
    status: "Available",
  },
  {
    id: "TL005",
    name: "Hamza Malik",
    phone: "0312-7654321",
    city: "Rawalpindi",
    experience: "4 Years",
    currentOrders: 175,

    specialization: "Kids Wear",
    completedOrders: 110,
    activeOrders: 2,
    rating: 4.5,
    status: "Busy",
  },
  {
    id: "TL006",
    name: "Hassan Shah",
    phone: "0307-2223344",
    city: "Multan",
    experience: "7 Years",
    currentOrders: 175,

    specialization: "Formal Wear",
    completedOrders: 210,
    activeOrders: 0,
    rating: 4.8,
    status: "Available",
  },
  {
    id: "TL007",
    name: "Zain Ali",
    phone: "0335-5557788",
    city: "Sialkot",
    experience: "3 Years",
    specialization: "Abayas",
    currentOrders: 175,

    completedOrders: 95,
    activeOrders: 3,
    rating: 4.4,
    status: "Busy",
  },
  {
    id: "TL008",
    name: "Saad Iqbal",
    phone: "0310-1112233",
    city: "Peshawar",
    experience: "9 Years",
    specialization: "Sherwani",
    currentOrders: 175,

    completedOrders: 290,
    activeOrders: 0,
    rating: 4.9,
    status: "Available",
  },
  {
    id: "TL009",
    name: "Imran Sheikh",
    phone: "0322-3344556",
    city: "Hyderabad",
    experience: "6 Years",
    specialization: "Women's Dresses",
    currentOrders: 175,
    completedOrders: 175,
    activeOrders: 5,
    rating: 4.6,
    status: "Busy",
  },
  {
    id: "TL010",
    name: "Farhan Qureshi",
    phone: "0309-9988776",
    city: "Gujranwala",
    experience: "12 Years",
    specialization: "Designer Wear",
    currentOrders: 175,
    completedOrders: 410,
    activeOrders: 0,
    rating: 5.0,
    status: "Available",
  },
];

export default tailorsData;