const tailorMeasurementsData = [
  {
    id: "M001",
    customer: "Ayesha Khan",
    orderId: "#1001",
    dress: "Bridal Lehenga",
    chest: 38,
    waist: 32,
    hips: 40,
    length: 54,
    shoulder: 15,
    sleeve: 22,
    notes: "Loose fitting on sleeves",
  },
  {
    id: "M002",
    customer: "Fatima Ali",
    orderId: "#1002",
    dress: "Silk Maxi",
    chest: 36,
    waist: 30,
    hips: 38,
    length: 58,
    shoulder: 14,
    sleeve: 21,
    notes: "Full length, deep neck",
  },
  {
    id: "M003",
    customer: "Sana Ahmed",
    orderId: "#1003",
    dress: "3 Piece Suit",
    chest: 40,
    waist: 34,
    hips: 42,
    length: 42,
    shoulder: 16,
    sleeve: 23,
    notes: "Straight trouser",
  },
  {
    id: "M004",
    customer: "Hira Noor",
    orderId: "#1004",
    dress: "Party Frock",
    chest: 34,
    waist: 28,
    hips: 36,
    length: 48,
    shoulder: 13,
    sleeve: 19,
    notes: "Flared bottom",
  },
  {
    id: "M005",
    customer: "Zara Malik",
    orderId: "#1005",
    dress: "Chiffon Lehenga",
    chest: 37,
    waist: 31,
    hips: 39,
    length: 52,
    shoulder: 15,
    sleeve: 20,
    notes: "Heavy embroidery blouse",
  },
];

export default tailorMeasurementsData;
